# Generated by Django 5.0.6 on 2024-08-08 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='Career',
            new_name='career',
        ),
    ]
