# Generated by Django 5.0.6 on 2024-08-08 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0001_initial'),
        ('period', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='level',
            field=models.CharField(choices=[('TSU', 'Tecnico Superior'), ('Ing', 'Ingenieria'), ('Lic', 'Licenciatura'), ('M', 'Maestria')], max_length=50),
        ),
        migrations.AlterField(
            model_name='subject',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='period.semester', verbose_name='Cuatrimestre'),
        ),
    ]
