# Generated by Django 5.0.6 on 2024-07-15 19:05

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0002_alter_career_options_alter_subject_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Hoja de Asignatura'),
        ),
    ]
